-- Expand country list to cover all of Europe
insert into public.countries (name, code) values
  ('Albania', 'AL'),
  ('Andorra', 'AD'),
  ('Armenia', 'AM'),
  ('Azerbaijan', 'AZ'),
  ('Belarus', 'BY'),
  ('Belgium', 'BE'),
  ('Bulgaria', 'BG'),
  ('Cyprus', 'CY'),
  ('Denmark', 'DK'),
  ('Estonia', 'EE'),
  ('Finland', 'FI'),
  ('Georgia', 'GE'),
  ('Iceland', 'IS'),
  ('Ireland', 'IE'),
  ('Kosovo', 'XK'),
  ('Latvia', 'LV'),
  ('Liechtenstein', 'LI'),
  ('Lithuania', 'LT'),
  ('Luxembourg', 'LU'),
  ('Malta', 'MT'),
  ('Moldova', 'MD'),
  ('Monaco', 'MC'),
  ('North Macedonia', 'MK'),
  ('Norway', 'NO'),
  ('Poland', 'PL'),
  ('Romania', 'RO'),
  ('Russia', 'RU'),
  ('San Marino', 'SM'),
  ('Slovakia', 'SK'),
  ('Sweden', 'SE'),
  ('Switzerland', 'CH'),
  ('Ukraine', 'UA'),
  ('Vatican City', 'VA')
on conflict (code) do nothing;
